listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8085;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html/live;
        hls_fragment    3;
        hls_window      60;
    }

    dvr {
        enabled         on;
        dvr_path        ./objs/nginx/html/recordings/[stream].mp4;
        dvr_plan        session;
    }

    http_hooks {
        enabled         on;
        on_publish      https://82e8-200-68-191-11.ngrok-free.app/api/streams/validate-key;
        on_unpublish    https://82e8-200-68-191-11.ngrok-free.app/api/streams/stop;
        on_dvr          https://82e8-200-68-191-11.ngrok-free.app/api/streams/dvr-notify;
    }
}
